description = "Building responsive, accessible websites"
postsPerPage = 10
defaultAuthor = "alfred"
newsletterAction = "/.netlify/functions/subscribe"
googleAnalytics = "G-9DYQ9R1F2M"  # Your GA4 ID
date_format = "2 Jan 2006"

[dev]
    enableDebug = true

[cusdis]
  host = "https://cusdis.com"
  appId = "a97f5053-8835-478b-b98b-05ee0c62fb47"
