description = "Building responsive, accessible websites"
postsPerPage = 5
defaultAuthor = "alfred"
newsletterAction = "/.netlify/functions/subscribe"
contactAction = "/.netlify/functions/contact"
date_format = "2 Jan 2006"
nameParticles = ["van", "de", "der", "den", "het", "ter", "te", "ten", "op", "in", "aan", "'t"]

[dev]
    enableDebug = true

[cusdis]
  host = "https://cusdis.com"
  appId = "a97f5053-8835-478b-b98b-05ee0c62fb47"
